### ISSUE TITLE
Onclose function called 4 times

### ISSUE THREAD

**Issue by drksparta** [Kinle/MultiStep.js#2]
Why is the onclosed function getting called like 4 times?

**Comment by rathindrabera** [comment]
@drksparta I think this happened because the `_onClose()` is called two times in `_buildModal()` **(line no 144-150 in MultiStep.js)**

` this.element.on('hide.bs.modal', function() {`
`       $this._initialModal();`
`       $this._onClose();`
`   }).on('hidden.bs.modal', function() {`
`       $this._initialModal();`
`       $this._onClose();`
`})`
@Kinle please check the issue
